# 예외처리

```C
MyData md;  
try {  
    //예외처리가 적용될 실행문입니다.
   md = GetNetworkResource();  
}  
catch (const networkIOException& e) {  
    //networkIOException 예외가 발생하면 이리로..
   cerr << e.what();  
}  
catch (const myDataFormatException& e) {  
    //myDataFormatException 예외가 발생하면 이리로..
   cerr << e.what();  
}  
  
MyData GetNetworkResource()  
{  
   if (IOSuccess == false)  
      throw networkIOException("Unable to connect"); 
      //throw을 이용해 예외를 발생시키고 있습니다.
   if (readError)  
      throw myDataFormatException("Format error");   
      //throw을 이용해 예외를 발생시키고 있습니다.
}  

```

> try블록은 예외를 평가 합니다.

> catch는 발생한 예외를 전달받습니다. Exception으로 예외를 받습니다.

> throw는 임의적으로 예외를 발생시킵니다.